spring:
  application:
    name: ExpenseShare

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE} # Maximum number of connections in the pool
      minimum-pool-size: ${DB_MIN_POOL_SIZE} # Minimum number of connections in the pool
      minimum-idle: ${DB_MIN_IDLE} # Minimum number of idle connections in the pool
      idle-timeout: ${DB_IDLE_TIMEOUT} # Maximum time that a connection can be idle in the pool
      connection-timeout: ${DB_CONNECTION_TIMEOUT} # Maximum time to wait for a connection from the pool
      pool-name: ${DB_POOL_NAME} # Name of the connection pool


  jpa:
    show-sql: true

